---
abstract: 'Provides an easy to have info of the browser.'
author:
  - 'Natal Ngétal'
build_requires:
  Dancer2::Test: 0
  Data::Dumper: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-BrowserDetect
requires:
  Dancer: 1.2001
  Dancer2: 0
  Dancer2::Plugin: 0
  HTTP::BrowserDetect: 0
  strict: 0
  warnings: 0
version: 1.131620
